name: Update documentation.yml
on:
  push:
    branches:
    - main
    paths:
    - docs/**
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'manual'
        type: choice
        options:
        - manual
        - info
        - warning
        - debug

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.8' 
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Install dependencies
      run: |
          pip install -r docs/requirements.txt
    - name: List directories
      run: |
          ls -la
    - name: Build Sphinx Documentation
      run: |
          sphinx-build -b html docs/ docs/_build/7ecafa3f19d05b4e9da98f734fd69aca7baa4965
    - name: Add files
      run: |
          echo "fedstellar.enriquetomasmb.com" > docs/_build/CNAME
    - uses: actions/checkout@v4
      with:
        ref: gh-pages
        path: gh-pages
    - name: Copy documentation to the gh-pages branch
      run: |
        cp -r docs/_build/* gh-pages/
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        directory: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
